# We don't need a separate job for building the Angular files, since the mvn compile command already does this due to our configuration.
# The proper output directory for the built files is set in angular/src/main/resources/ui/angular.json
build-frontend:
  image: lucaired/onlineide-frontend:latest # For this job, use a different image than the globally defined one. This way we don't have to install the Angular dependencies manually.
  stage: build
  variables:
    MICROSERVICE_DIR: "frontend"
  script:
    - cd $MICROSERVICE_DIR/src/main/resources/ui
    - npm ci
    - cd $CI_PROJECT_DIR/$MICROSERVICE_DIR
    - mvn $MAVEN_CLI_OPTS clean compile
  artifacts:
    paths:
      - $MICROSERVICE_DIR/src/main/resources/static/*

package-frontend:
  extends: .template-package
  variables:
    MICROSERVICE_DIR: "frontend"