version: '2.1'

services:
  postgres:
    image: library/postgres:12-alpine
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test

volumes:
  data:
