build-compiler:
  extends: .template-build
  variables:
    MICROSERVICE_DIR: "compiler"

test-compiler:
  stage: test
  # Install gcc in order to execute the integration and E2E tests
  # TODO: This can probably be removed later if we use our own Docker images with pre-installed packages
  before_script:
    - apt-get update
    - apt-get --yes install build-essential
  script:
    - cd compiler
    - mvn $MAVEN_CLI_OPTS test
  needs:
    - build-compiler

package-compiler:
  extends: .template-package
  variables:
    MICROSERVICE_DIR: "compiler"
  needs:
    - test-compiler