spring:
  application:
    name: ui-service
server:
  port: ${PORT:8400}
  servlet:
    contextPath: /ui
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}