spring:
  application:
    name: project-service
  profiles:
    active: ${SPRING_PROFILE:dev}
server:
  port: ${PORT:8100}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

# Resource servers are also just OAuth clients, so they need the following configuration as well as the gateway.
# The token relay in the gateway only ensures that the context is passed on; each resource server must handle and verify it on its own.
security:
  oauth2:
    client:
      clientId: ${OAUTH_CLIENT_ID}
      clientSecret: ${OAUTH_CLIENT_SECRET}
      accessTokenUri: https://gitlab.lrz.de/oauth/token
      userAuthorizationUri: https://gitlab.lrz.de/oauth/authorize
      scope:
        - read_user
        - api
    resource:
      userInfoUri: https://gitlab.lrz.de/api/v4/user