# We don't need a separate job for building the Angular files, since the mvn compile command already does this due to our configuration.
# The proper output directory for the built files is set in angular/src/main/resources/ui/angular.json
build-ui:
  image: lucaired/onlineide-frontend:latest # For this job, use a different image than the globally defined one. This way we don't have to install the Angular dependencies manually.
  stage: build
  variables:
    MICROSERVICE_DIR: "ui"
  script:
    - cd $CI_PROJECT_DIR/$MICROSERVICE_DIR
    - mvn $MAVEN_CLI_OPTS clean compile -e

package-ui:
  extends: .template-package
  image: lucaired/onlineide-frontend:latest
  variables:
    MICROSERVICE_DIR: "ui"
  needs:
    - build-ui
